#! /bin/bash
#
### BEGIN INIT INFO
# Provides:				Teamspeak 3 Server
# Required-Start:		$network
# Required-Stop:		$network
# Default-Start:		2 3 4 5
# Default-Stop:			0 1 6
# Short-Description:	Provides Teamspeak 3 Server for communication
### END INIT INFO

USER="teamspeak"
TSPATH="/opt/teamspeak"

do_start () {
	su - ${USER} -c "${TSPATH}/ts3server_startscript.sh start"
}

do_stop () {
	su - ${USER} -c "${TSPATH}/ts3server_startscript.sh stop"
}

do_status () {
	su - ${USER} -c "${TSPATH}/ts3server_startscript.sh status"
}

case "$1" in
		start)
				do_start
				;;
		stop)
				do_stop
				;;
		restart)
				do_stop
				do_start
				;;
		status)
				do_status
				;;
		*)
				echo "Usage: $0 {start|stop|restart|status}"
				exit 3
				;;
esac
